### ISSUE TITLE
Editing cards

### ISSUE THREAD

**Issue by CasparVelsen** [CasparVelsen/recaught#29]
## Value Preposition

**As a User**
**I need** a way to edit my cards
**to be able to** change data and correct mistakes
## Description

![capstone-edit](https://user-images.githubusercontent.com/98737059/162693126-7f01d6f9-5501-4f44-91a9-6b4405152c3c.png)

## Acceptance Criteria

- [ ] onEdit the user can edit his/her data
- [ ] on Edit the edit button changes to "submit changes"
- [ ] onDubmitChanges changed data updates card data in backend

## Tasks

- [ ] work on new branch
- [ ] create Buttons (edit, submit)
- [ ] write functions for edit and submit
- [ ] create backend logic to update data
